#@ [config.yml template file] 
#@ For reordering OpGuard 1.x and 2.x's config
#@
#@ Schema:
#@ - @(<previous config.yml path> | <previous config.yml path> | ... | <default value>)
#@
#@ About:
#@ - Every '@()' statement will be replaced with the previous configuration file's value.
#@ - Multiple options may be defined within each '@()' statement, where the last option is the default value.
#@ - All '#@' comments will be ignored in the newly-created config.yml file.

# --------------------- #
# OpGuard Configuration #
# --------------------- #

# Duration of time (in ticks) that OpGuard should verify the op list.
# Remember: 20 ticks = 1 second, so 4 ticks = 1/5 of a second.
# This value cannot be negative or zero.
# Default: 4
inspection-interval: @(inspection-interval | 4)

# If true, OpGuard will only op players if they're online.
# Default: true
only-op-if-online: @(only-op-if-online | true)

# If true, OpGuard's password can be managed with in-game commands.
# If false, only console can modify OpGuard's password.
# Default: true
manage-password-in-game: @(manage.password-in-game | true)

# If true, OpGuard will disable plugins that have been caught setting op.
# Default: true
disable-malicious-plugins-when-caught: true

# If true, OpGuard will rename plugin .jar files that have been caught 
# setting op so they cannot re-enable.
# This will only occur if the option above is also enabled (plugin disabling).
# Default: true
rename-malicious-plugins-when-caught: true

# If true, OpGuard will shut the server down if it is disabled.
# Enable this option if you don't want other plugins to disable OpGuard.
# Default: false
shutdown-on-disable: @(shutdown-on-disable | false)

# If true, OpGuard will lock its commands, preventing new operators from
# being added and preventing its password from being modified.
# The only way to unlock is to change the value to false and restart the server.
# Default: false
lock: false

# ----------- #
#   LOGGING   #
# ----------- #

# If false, all OpGuard logging will be disabled.
# Default: true
enable-logging: @(log.enabled | true)

#@# Log status messages.
#@# Default: true
#@log-status-messages: @(log.status | true)

# Log when a plugin attempts to give op.
# Default: true
log-plugin-attempts: @(log.plugin-attempt | true)

# Log when the console attempts to give op.
# Default: true
log-console-attempts: @(log.console-attempt | true)

# Log when a player attempts to use /op.
# Default: true
log-player-attempts: @(log.player-attempt | true)

# ------------------------- #
#   MESSAGES AND WARNINGS   #
# ------------------------- #

# Prefix for warnings.
# Default: '&cOpGuard (&4&lWarning&c)&7:'
warn-prefix: '&cOpGuard (&4&lWarning&c)&7:'

# Color to use in warnings for emphasis
# Default: '&c'
warn-emphasis-color: '&c'

# If true, OpGuard will display warnings whenever a plugin attempts to give op.
# Default: true
warn-plugin-attempts: @(warn.plugin-attempt | true)

# If true, OpGuard will display warnings whenever console attempts  to use /op.
# Default: true
warn-console-op-attempts: @(warn.console-attempt | true)

# If true, OpGuard will display warnings whenever console incorrectly uses /opguard.
# Default: true
warn-console-opguard-attempts: @(warn.console-attempt | true)

# If true, OpGuard will display warnings whenever a player attempts to use /op.
# Default: true
warn-player-op-attempts: @(warn.player-attempt | true)

# If true, OpGuard will display warnings whenever a player incorrectly uses /opguard.
# Default: true
warn-player-opguard-attempts: @(warn.player-attempt | true)

# Prefix for security warnings.
# Default: '&eOpGuard (&6&lSecurity&e)&7:'
security-prefix: '&eOpGuard (&6&lSecurity&e)&7:'

# If true, OpGuard will display warnings when it lacks a password.
# Default: true
enable-security-warnings: @(warn.security-risk | true)

# Prefix for general status messages.
# Default: '&aOpGuard (&2&lOkay&a)&7:'
okay-prefix: '&aOpGuard (&2&lOkay&a)&7:'

# --------------- #
#   PUNISHMENTS   #
# --------------- #

# If true, OpGuard will punish players that other plugins attempt to op.
# Default: true
punish-plugin-attempts: @(punish.plugin-attempt | true)

# If true, OpGuard will punish players when the console attempts to use /op.
# Default: true
punish-console-op-attempts: @(punish.console-attempt | true)

# If true, OpGuard will punish players when console incorrectly uses /opguard.
# Default: false
punish-console-opguard-attempts: false
  
# A list of commands to run when punishing a player.
# Default:
# - ban %player% Attempting to gain op
punishment-commands:
- @(punish.command | ban %player% Attempting to gain op)

# ----------- #
#   METRICS   #
# ----------- #

metrics: @(metrics | true)

# Do not modify this value, it may affect config updates in the future.
version: ${version}
