main: org.github.guardedoperators.opguard.OpGuard
name: OpGuard
version: ${project.version}
website: https://github.com/GuardedOperators/OpGuard
loadbefore: [ProtocolLib, Vault, Essentials, EssentialsX, PlugMan, PermissionsEx, GroupManager]
api-version: 1.13
