main: com.github.guardedoperators.opguard.OpGuard
name: OpGuard
version: ${project.version}
api-version: 1.13

description: Password-protected op.
website: https://github.com/GuardedOperators/OpGuard

load: STARTUP
loadbefore: [ProtocolLib, Vault, Essentials, EssentialsX, PlugMan, PermissionsEx, GroupManager, LuckPerms]
